name: inventory
services:
  api:
    container_name: inventory_api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - api-node-modules:/usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 3001:3000
  ##fe:
  ##  container_name: inventory_fe
  ##  build:
  ##    dockerfile: Dockerfile
  ##    context: "C:/Users/kbong/projects/react/inventory_fe/inventory_fe"
  ##  volumes:
  ##    - "C:/Users/kbong/projects/react/inventory_fe/inventory_fe:/usr/src/app"
  ##    - fe-node-modules:/usr/src/app/node_modules
  ##  command: npm run start
  ##  environment:
  ##     - CHOKIDAR_USEPOLLING=true
  ##     - WATCHPACK_POLLING=true
  ##  ports:
  ##    - 3001:3001
  postgres:
    image: postgres
    restart: always
    container_name: inventory_db
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    volumes:
      - inventorydb:/var/lib/postgresql/data
volumes:
  api-node-modules:
  fe-node-modules:
  inventorydb: